In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

# Modelling
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression, RidgeClassifier, Lasso
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
import warnings

In [2]:
df = pd.read_csv('data/tech_job_skills_dataset.csv')

In [3]:
df.head()

,Job Role,Problem Solving,Communication,Teamwork,Creativity,Programming,System Design,Project Management,Cybersecurity,Machine Learning,Mobile Development,Web Development,Database Management,Networking,Cloud Computing,Data Analysis,Testing,UI/UX Design,Technical Writing
0,Game Developer,0,5,5,10,4,1,6,5,2,1,7,4,1,8,6,9,10,2
1,Technical Writer,9,6,7,9,6,0,1,4,8,1,0,5,9,0,2,10,10,9
2,Systems Analyst,3,9,4,9,10,7,0,7,0,1,5,0,4,9,2,0,7,5
3,Backend Developer,10,2,4,4,8,1,8,10,10,3,1,3,1,8,9,4,2,2
4,Technical Writer,8,6,10,8,0,4,3,2,7,9,7,7,2,2,6,7,5,1

In [5]:
X = df.drop(columns=['Job Role'],axis=1)

In [6]:
X.head()

,Problem Solving,Communication,Teamwork,Creativity,Programming,System Design,Project Management,Cybersecurity,Machine Learning,Mobile Development,Web Development,Database Management,Networking,Cloud Computing,Data Analysis,Testing,UI/UX Design,Technical Writing
0,0,5,5,10,4,1,6,5,2,1,7,4,1,8,6,9,10,2
1,9,6,7,9,6,0,1,4,8,1,0,5,9,0,2,10,10,9
2,3,9,4,9,10,7,0,7,0,1,5,0,4,9,2,0,7,5
3,10,2,4,4,8,1,8,10,10,3,1,3,1,8,9,4,2,2
4,8,6,10,8,0,4,3,2,7,9,7,7,2,2,6,7,5,1

In [7]:
print("Categories in 'job role' variable:     ",end=" " )
print(df['Job Role'].unique())

Categories in 'job role' variable:      ['Game Developer' 'Technical Writer' 'Systems Analyst' 'Backend Developer'
 'Data Scientist' 'DevOps Engineer' 'Full Stack Developer'
 'IT Support Specialist' 'Cloud Engineer' 'UI/UX Designer'
 'Frontend Developer' 'iOS Developer' 'Other' 'Database Administrator'
 'Product Manager' 'MLOps Engineer' 'QA Engineer' 'Network Engineer'
 'Cybersecurity Specialist' 'Android Developer']

In [8]:
y = df['Job Role']

In [9]:
y

0               Game Developer
1             Technical Writer
2              Systems Analyst
3            Backend Developer
4             Technical Writer
5               Data Scientist
6              DevOps Engineer
7            Backend Developer
8         Full Stack Developer
9        IT Support Specialist
10              Cloud Engineer
11              UI/UX Designer
12          Frontend Developer
13          Frontend Developer
14               iOS Developer
15                       Other
16      Database Administrator
17             Product Manager
18                       Other
19              Data Scientist
20              MLOps Engineer
21                 QA Engineer
22              UI/UX Designer
23              UI/UX Designer
24            Technical Writer
25      Database Administrator
26              UI/UX Designer
27                       Other
28            Network Engineer
29            Technical Writer
30               iOS Developer
31       IT Support Specialist
32            Technical Writer
33              Cloud Engineer
34              UI/UX Designer
35    Cybersecurity Specialist
36                 QA Engineer
37                 QA Engineer
38              Cloud Engineer
39                       Other
40    Cybersecurity Specialist
41              UI/UX Designer
42      Database Administrator
43              Game Developer
44              Game Developer
45              Game Developer
46       IT Support Specialist
47       IT Support Specialist
48      Database Administrator
49           Android Developer
Name: Job Role, dtype: object

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

# Define the numeric transformer
numeric_transformer = StandardScaler()

# Since all features are numerical, we apply StandardScaler to all of them
preprocessor = ColumnTransformer(
    transformers=[
        ("StandardScaler", numeric_transformer, X)
    ]
)

In [12]:
X = preprocessor.fit_transform(X)

ValueError: No valid specification of the columns. Only a scalar, list or slice of all integers or all strings, or boolean mask is allowed

In [18]:
X.shape

(50, 18)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((40, 18), (10, 18))

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def evaluate_model(true, predicted):
    accuracy = accuracy_score(true, predicted)
    precision = precision_score(true, predicted, average='weighted')
    recall = recall_score(true, predicted, average='weighted')
    f1 = f1_score(true, predicted, average='weighted')
    conf_matrix = confusion_matrix(true, predicted)
    
    return accuracy, precision, recall, f1, conf_matrix

In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Initialize the Decision Tree model
dt_model = DecisionTreeClassifier()  # Use the correct model name

# Fit the model to the training data
dt_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = dt_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred) * 100

# Print the accuracy of the model
print("Accuracy of the model is %.2f%%" % accuracy)

Accuracy of the model is 20.00%